### ISSUE TITLE
Cannot Launch App

### ISSUE THREAD

**Issue by ConnerPope** [reactide/reactide#130]
Steps to reproduce:
OS: Mac OS X

1. Download application

2. Open terminal

3. `npm install`

4. `npm start`

Electron opens, but the application fails to boot. It just loads a blank grey background.

**Comment by Cmoen11** [comment]
Since you're using an unix system, try sudo npm install

**Comment by pRivAte12** [comment]
OS : Mac OSX
npm : 5.6.0
node : 8.5.0

I have same issue here.
It loads a blank background

**Comment by pRivAte12** [comment]
Solved!

The problem was that index.html was unable to find ../dist/bundle.js

So I used webpack to generate bundle.js in dist folder. 
Before launching electron, you have to build files in renderer directory.

package.json
`"scripts": {
    "test": "mocha --compilers js:babel-register test/test.js",
    "start": "cross-env NODE_ENV=production electron .",
    "dev-start": "cross-env NODE_ENV=development electron .",
    "dev": "webpack-dev-server --inline --content-base ./renderer",
    "build": "webpack"
  },`

I just add build scripts in package.json.

1. npm run build
2. npm start

Then it works!
