### ISSUE TITLE
Atom integration

### ISSUE THREAD

**Issue by aemino** [reactide/reactide#36]
This project looks very exciting -- but I'm still wondering one thing. A lot of the proposed UI looks very similar to Atom. Is there a reason this project is being developed as a standalone IDE rather than an extension package for Atom? I feel it would be more convenient for users if they could just install a plugin on Atom. It might also allow you to reach a wider user audience, since Atom is already widely adopted.

**Comment by JiniHendrix** [comment]
Yes, we were highly inspired by atom's sleek design. But we have been getting alot of confusion about it being an Atom package and are considering a different theme. 

We wanted to make an IDE to streamline the entire React development process by consolidating dev tools and providing quick and easy React project creation with hot reloading at the click of a button.

**Comment by amonks** [comment]
I think you could make an IDE that streamlines the react development process and consolidates dev tools and provides quick and easy project creation _and also benefit from atom's editor and plugin ecosystem_.

For example, Facebook's IDE, [nuclide](https://nuclide.io/) is implemented as an atom package. Users get all the benefits of an integrated ide, but can also use the atom add-ons they know and love, and benefit from all of Atom's bugfixes and development down the line, even if Nuclide isn't updated.

The potential benefits are huge, and I can't think of any downsides. It sounds like you _have_ thought of downsides. I'd love to hear what they are.

**Comment by aemino** [comment]
I don't think there's really any confusion about this being an Atom package, and I don't think there's anything wrong with taking inspiration from the Atom theme.

My main point is that I think there are a lot of potential upsides that could be gained from simply writing a package meant for Atom. It saves you a lot of effort that you'll put into writing editor code, and will make Reactide much easier to adopt. It will also greatly benefit from the diverse package ecosystem that Atom has.

**Comment by markmarcelo** [comment]
Atom and VS Code packages definitely sound like a great idea!

**Comment by ambethia** [comment]
> I don't think there's really any confusion about this being an Atom package

I took one look at the screenshot and thought "oh cool it's an Atom package, like Nuclide", I was disappointed to see it wasn't. I'm still interested in trying it, but, admittedly less excited than I was thinking it was built in Atom.

**Comment by kenaniah** [comment]
Love the idea, but also disappointed to hear that this isn't an atom package. Last thing I want to do is install yet another editor. For me, not being integrated with atom is actually a non-starter.

**Comment by MindRave** [comment]
Huge thumbs up for this. 👍  I agree with the other posters, while this definitely looks awesome 😉 , downloading a separate IDE just for React projects is a bit overkill (for my personal workflow).

**Comment by wonderbeyond** [comment]
Also disappointed to hear that this isn't an atom package.

**Comment by adrianoresende** [comment]
Well, interesting issue, I could not use Atom because of the performance.
I think it's fair that he made Atom over (less errors and bugs), that I cleaned everything up and left it just reactive.
In my opinion, the only good side to not having done with Atom is not to mix with other codes and plugins that would not be useful, just deploy what is useful for react and performance as fast as possible (I do not know if it can make a difference).

**Comment by mogarick** [comment]
VSCode and Atom are build on top of Electron but each of them implemented different strategies for the whole editor thing. I used both and stayed with VSCode because of its better performance.
Is ReactIDE based on Electron also? Are you implementing a different approach than the ones from Atom or VSCode or are you building on top of one of them?
If your approach is different it would be great to know what are you making different and if this new approach makes things better in the performance field or any other important field.

**Comment by markmarcelo** [comment]
Atom and VS Code package implementation will be in the production pipeline.

In the meantime, the single developer environment allows us to explore new tools through cross-utilization.

**Comment by seanpan** [comment]
@markmarcelo Sounds really good idea to have two implementations. But still curious how can that be achieved since most people who suggest a Atom/VSCode package version simply want to keep their frequently used plugins. Is there a plan to support those plugins in Reactide standalone version?
